language: cpp
cache: ccache
sudo: false

addons:
  homebrew:
    packages:
    - fftw
    - hdf5
    - ccache
    - boost-python3
    - cfitsio
    - wcslib
    update: true

env:
  global:
    - CCACHE_COMPRESS=1
    - CCACHE_CPP2=yes

matrix:
  include:
    - os: linux
      compiler: gcc
      env: DIST=ubuntu1604
      services: [docker]
      sudo: true
    - os: linux
      compiler: clang
      env: DIST=ubuntu1604
      services: [docker]
      sudo: true
    - os: linux
      compiler: gcc
      env: DIST=ubuntu1804
      services: [docker]
      sudo: true
    - os: linux
      compiler: clang
      env: DIST=ubuntu1804
      services: [docker]
      sudo: true
    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc

jobs:
  allow_failures:
  - os: osx

before_script:
  - ./.travis/before_script.sh

script:
  - ./.travis/script.sh
