os:
  - linux
  - osx

language: cpp

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Release CASACORE_CHECK=no
  - BUILD_TYPE=Debug CASACORE_CHECK=yes

install:
  - ./travis-deps.sh


before_script:
  - wget http://www.iausofa.org/2015_0209_F/sofa_f-20150209_a.tar.gz -O /tmp/sofa.tgz
  - tar -xzf /tmp/sofa.tgz
  - cd sofa/20150209_a/f77/src/ && make && make test && cd ../../../../
  - mkdir build
  - cd build
  - wget ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar
  - tar zxvf WSRT_Measures.ztar
  - cmake ..
      -DUSE_FFTW3=ON
      -DBUILD_TESTING=ON
      -DUSE_OPENMP=OFF
      -DUSE_HDF5=ON
      -DBUILD_PYTHON=ON
      -DDATA_DIR=$PWD
      -DSOFA_ROOT_DIR=$HOME
      -DCMAKE_BUILD_TYPE=$BUILD_TYPE

script:
  - make -j4
  - if [ $BUILD_TYPE == "Debug" ]; then export CASACORE_CHECK=yes; fi
  - make test
  - sudo make install
